### ISSUE TITLE
Importing the csv file?

### ISSUE THREAD

**Issue by cscd98** [AllenJB/PafUtils#1]
@AllenJB Hi, Thank you for this. Do you have any useful PHP files on importing the CSV file in the first place, e.g. to mysql?

**Comment by AllenJB** [comment]
Hi. No, I don't have that as a library. The current code I have is project specific and I didn't think it worth investing the time in refactoring that out as it's a relatively trivial task. It's the address assembling rules I had trouble with, so I thought that most useful to pull out as a library for others to use.
